# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

run:
  concurrency: 4
  timeout: 1m

linters-settings:
  importas:
    no-unaliased: true
    no-extra-aliases: false
  gocritic:
    enabled-checks:
      - importShadow
      - httpNoBody
      - paramTypeCombine
      - emptyStringTest
      - builtinShadow
      - exposedSyncMutex
    disabled-checks:
      - appendAssign
    enabled-tags:
      - diagnostic
    disabled-tags:
      - performance
      - style
      - experimental
      - opinionated
  stylecheck:
    checks: ["-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022"]
  goheader:
    template: |-
      Copyright (c) Abstract Machines
      SPDX-License-Identifier: Apache-2.0

linters:
  disable-all: true
  fast: true
  enable:
    - gocritic
    - gosimple
    - errcheck
    - govet
    - unused
    - goconst
    - godot
    - godox
    - ineffassign
    - misspell
    - stylecheck
    - whitespace
    - gci
    - gofmt
    - goimports
    - loggercheck
    - goheader
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - decorder
    - dogsled
    - errchkjson
    - errname
    - execinquery
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - gofumpt
    - goprintffuncname
    - importas
    - makezero
    - mirror
    - nakedret
    - dupword
