# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1

linters:
  disable-all: true
  fast: true
  enable:
    - goheader
    - godot
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - durationcheck
    - exhaustive
    - goconst
    - misspell
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - rowserrcheck
    - stylecheck
    - tenv
    - unconvert
    - unparam
    - wastedassign
    - containedctx
    - revive
    - gocritic
    - whitespace
    - errorlint
    - contextcheck
    - dogsled
    - errname
    - funlen
    - gci
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - loggercheck
    - nilnil
    - nilerr
    - nlreturn
